config/routes.rb
FindDrug::Application.routes.draw do
  root 'find#drug'
  post 'find/submit', :to => 'find#submit'
end

app/models/find.rb
class Find < ActiveRecord::Base
	validates_uniqueness_of :name

	# require 'csv'
	# @@parsed = nil

	# def self.parsed_drugs
	# 	if @@parsed 
	# 		return @@parsed
	# 	else
	# 		@@parsed = {}
	# 		drugs = CSV.read("formulary_items.csv", {:headers => true})
	# 		drugs.each do |drug|
	# 			whole_name = drug['name'].downcase
	# 			whole_name.sub!('/', ' ')
	# 			whole_name.sub!('-', ' ')
	# 			name_arr = whole_name.split(' ')
	# 			name_arr.each do |name|
	# 				if @@parsed[name]
	# 					if drug['brand_or_generic'].nil? || drug['carrier'].nil?
	# 						next
	# 					else 
	# 						unless @@parsed[name][:carrier].include?(drug['carrier'])
	# 							@@parsed[name][:brand_or_generic] << drug['brand_or_generic']
	# 							@@parsed[name][:carrier] << drug['carrier']
	# 						end
	# 					end
	# 				else
	# 					@@parsed[name] = {brand_or_generic: [drug['brand_or_generic']], carrier: [drug['carrier']]}
	# 				end	
	# 			end
	# 		end
	# 	end
	# 		@@parsed
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/find_controller.rb
class FindController < ApplicationController
	def drug
		# @drugs = Find.parsed_drugs

		render :drug
	end

	def submit
		name = drug_params['name']
		@drugs = Find.where('name like ?', "%#{name}%")
		# fail
		# if @drugs.count == 0
		# 	@results = nil
		# else
		# 	@results = @drugs
		# end
		render :submit
		# @drugs = Find.parsed_drugs
		# drug_params['name'].downcase!
		# if !@drugs[drug_params['name']]
		# 	@results = nil
		# else 
		# 	@results = { name: drug_params['name'] }
		# 	@results = @results.merge(@drugs[drug_params['name']])
		# end
		# render :submit
	end

	private

	def drug_params
		params.require(:find).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/views/find/drug.html.erb
<h1>Search for your drug</h1>

<form action="<%= find_submit_url %>" method="POST">
	<input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
	<div class="input-group">
	  <span class="input-group-addon" id="basic-addon1">A</span>
	  <input name="find[name]" type="text" class="form-control" placeholder="Type drug name..." aria-describedby="basic-addon1">
	</div>
</form>

<% if @results %>
	<% @results.each do |result| %>
		<li><%= result.tier %></li>
		<li><%= result.carrier %></li>
	<% end %>
<% end %>

app/views/find/submit.html.erb
<br>
	<a href="<%= root_url %>"><span class="glyphicon glyphicon-arrow-left"></span>  Back to search</a>

<div class="panel-body">
	<% if !@drugs.empty? %>
	<div class="panel-heading">
	    <h3 class="panel-title">We found your drug! These carriers carry your drug. </h3>
	</div>
	<ul>
		<li><span class="generic">Green</span> is cheap!</li>
		<li><span class="brand">Red</span> is expensive!</li>
	</ul>
	<div class="results-list">
		<% @drugs.each do |drug| %>
		Name: <%= drug.name.capitalize %><br>
		Carrier: <%= drug.carrier.capitalize %><br>
		State: <%= drug.state.capitalize %><br>
		Tier: <%= drug.tier %><br>
		Brand: <%= drug.brand_or_generic %><br><br>
		<% end %>
	</div>
	<% else %>
	  <p>We didn't find your drug...</p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindDrug</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= html_import_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= flash[:notice] ? flash[:notice] : '' %>
    <core-drawer-panel>
    <core-header-panel drawer>
      <core-toolbar>
        <div>SimplyFound</div>
      </core-toolbar>
      <div> Drawer content... </div>
    </core-header-panel>
    <core-header-panel main>
      <core-toolbar>
        <core-icon-button icon="menu" core-drawer-toggle></core-icon-button>
        <div>Search</div>
      </core-toolbar>
      <div> Main content... </div>
    </core-header-panel>
  </core-drawer-panel>
</div>
</body>
</html>